In [1]:
import pandas as pd
import numpy as np

import data set

In [2]:
borrowings = pd.read_csv("../../data/processed/library_borrowings.csv")
catalogue = pd.read_csv("../../data/processed/library_catalogue.csv")
inventory = pd.read_csv("../../data/processed/library_inventory.csv")

In [3]:
print("Borrowings:", borrowings.shape)
print("Catalogue:", catalogue.shape)
print("Inventory:", inventory.shape)

Borrowings: (421, 4)
Catalogue: (565, 4)
Inventory: (4176, 9)

In [4]:
borrowings.info()
catalogue.info()
inventory.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421 entries, 0 to 420
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Title               421 non-null    object
 1   Reader_num          421 non-null    object
 2   category            421 non-null    int64
 3   borrowing_duration  421 non-null    int64
dtypes: int64(2), object(2)
memory usage: 13.3+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 565 entries, 0 to 564
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ISBN/ISSN   565 non-null    object
 1   Title       565 non-null    object
 2   Author      565 non-null    object
 3   Copy Count  565 non-null    int64
dtypes: int64(1), object(3)
memory usage: 17.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4176 entries, 0 to 4175
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Inventory Number  4176 non-null   object
 1   Title             4176 non-null   object
 2   Author            4176 non-null   object
 3   Editor            4176 non-null   object
 4   Edition Date      4176 non-null   object
 5   Edition Location  4176 non-null   object
 6   Acquisition Mode  4176 non-null   object
 7   Status            4176 non-null   object
 8   Localisation      4176 non-null   object
dtypes: object(9)
memory usage: 293.8+ KB

In [5]:
borrowings.head()

,Title,Reader_num,category,borrowing_duration
0,EXERCICES CORRIGÉS D'ANALYSE : 1ÈRE ANNÉE LMD,5817912,1,15
1,EXERCICES D'ALGÈBRE ET D'ANALYSE : 154 EXERCIC...,5754033,1,17
2,EXERCICES D'ALGÈBRE ET D'ANALYSE : 154 EXERCIC...,5113394,1,15
3,EXERCICES D'ALGÈBRE ET D'ANALYSE : 154 EXERCIC...,6092419,1,15
4,EXERCICES ET PROBLÈMES D'ALGORITHMIQUE : 144 É...,8354464,3,7

In [ ]:
catalogue.head()

,ISBN/ISSN,Title,Author,Copy Count
0,9782855576558,10 CLÉS POUR COMPRENDRE LE SOL,RAOUL CALVET,3
1,9782100824199,100 FICHES POUR BIEN DÉMARRER EN PRÉPA,MARIE-VIRGINIE SPELLER,2
2,9782100725106,50 [CINQUANTE]CLÉS POUR COMPRENDRE LA PHYSIQUE,"BAKER, JOANNE",2
3,9782729839406,8 ANS DE PROBLÈMES CORRIGÉS DE MATHÉMATIQUES P...,FRANCHINI JEAN,2
4,9780321794772,A FIRST COURSE IN PROBABILITY,"ROSS, SHELDON M.",3

In [ ]:
inventory.head()

,Inventory Number,Title,Author,Editor,Edition Date,Edition Location,Acquisition Mode,Status,Localisation
0,624,"100 FICHES POUR BIEN DÉMARRER EN PRÉPA, 2021-2...","SPELLER, MARIE-VIRGINIE.",MALKOFF,2021.0,PARIS,ACHAT,CONSULTATION SUR PLACE,ENSIA
1,849,400 EXERCICES CORRIGÉS D'ALGÈBRE AVEC RAPPELS ...,"AASSILA, MOHAMMED",ELLIPSES,2014.0,PARIS,DON,PRÊT EXTERNE,ENSIA
2,1387,50 [CINQUANTE]CLÉS POUR COMPRENDRE LA PHYSIQUE,"BAKER, JOANNE",DUNOD,2015.0,PARIS,DON,PRÊT EXTERNE,ENSIA
3,941,50 [CINQUANTE]CLÉS POUR COMPRENDRE LA PHYSIQUE,"BAKER, JOANNE",DUNOD,2015.0,PARIS,PASSIF,PRÊT EXTERNE,ENSIA
4,1014,8 ANS DE PROBLÈMES CORRIGÉS DE MATHÉMATIQUES P...,FRANCHINI JEAN,UNKNOWN_EDITOR,2008.0,PARIS,ACHAT,PRÊT EXTERNE,ENSIA

In [8]:
borrowings.describe(include="all")

,Title,Reader_num,category,borrowing_duration
count,421,421,421.000000,421.000000
unique,132,271,NaN,NaN
top,COURS D'ALGÈBRE ET EXERCICES CORRIGÉS,5817912,NaN,NaN
freq,57,3,NaN,NaN
mean,NaN,NaN,1.650831,16.268409
std,NaN,NaN,0.922822,20.145818
min,NaN,NaN,0.000000,7.000000
25%,NaN,NaN,1.000000,15.000000
50%,NaN,NaN,1.000000,15.000000
75%,NaN,NaN,2.000000,15.000000
max,NaN,NaN,4.000000,302.000000

In [9]:
catalogue.describe(include="all")

         ISBN/ISSN    Title         Author  Copy Count
count          565      565            565  565.000000
unique         564      528            505         NaN
top     1077321600  ANALYSE  HAZI MOHAMMED         NaN
freq             2        5             10         NaN
mean           NaN      NaN            NaN    5.437168
std            NaN      NaN            NaN   17.820670
min            NaN      NaN            NaN    0.000000
25%            NaN      NaN            NaN    1.000000
50%            NaN      NaN            NaN    2.000000
75%            NaN      NaN            NaN    3.000000
max            NaN      NaN            NaN  174.000000

In [10]:
inventory.describe(include="all")

,Inventory Number,Title,Author,Editor,Edition Date,Edition Location,Acquisition Mode,Status,Localisation
count,4176,4176,4176,4176,4176,4176,4176,4176,4176
unique,4176,695,610,74,59,37,3,3,2
top,624,FONCTIONS RÉELLES D'UNE VARIABLE RÉELLE : DÉRI...,HAZI MOHAMMED,OPU,2018.0,ALGER,ACHAT,PRÊT EXTERNE,ENSIA
freq,1,174,1075,2354,1017,2705,3718,3925,4166